name: deploy-in-production

run-name: Pulling changes and build
on:
  pull_request_target:
    branches: [main]
    types:
      - closed

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Clean Up Application
        run: |
          rm -rf .next/
          rm -rf dist/

      - name: Build application
        run: |
          git pull
          npm i
          npm run build

      - name: Restart PM2
        run: |
          pm2 stop radix-web-interface
          pm2 start radix-web-interface

      - name: Deploy to Production Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
